---
- hosts: "{{target}}"
  tasks:
    - name: Update packages
      apt:
        upgrade: dist

    - name: Install latest version of "openjdk-11-jdk" ignoring "install-recommends"
      apt:
        name: openjdk-11-jdk
        state: latest
        install_recommends: no

    - name: Creates directory
      file:
        path: '/home/vagrant/app'
        state: directory
        owner: "vagrant"
        group: "vagrant"

    - name: Unpack deploy files
      unarchive:
        src: "/tmp/service-cloud-message.tgz"
        dest: "/home/vagrant/app"
        owner: "vagrant"
        group: "vagrant"

    - name: List Packages Dir
      find:
        paths: "/home/vagrant/app"
      register: output

    - debug:
        var: output