---
- hosts: "{{target}}"
  tasks:
    - name: Update packages
      apt:
        upgrade: dist

    - name: Install latest version of "openjdk-11-jdk" ignoring "install-recommends"
      apt:
        name: openjdk-11-jdk
        state: latest
        install_recommends: no